let accountId=localStorage.getItem('bhachuAccount'),name=localStorage.getItem('bhachuName'),loginMode=false;
const $=x=>document.getElementById(x);
function showApp(){ $('auth').classList.add('hidden');$('app').classList.remove('hidden');$('user').textContent=name||'';load(); }
$('switch').onclick=()=>{loginMode=!loginMode;$('authTitle').textContent=loginMode?'Sign in to BHACHU FX':'Create your trading account';$('name').style.display=loginMode?'none':'block';$('authBtn').textContent=loginMode?'Sign in':'Create account';$('switch').textContent=loginMode?'Need an account? Create one':'Already registered? Sign in'};
$('authBtn').onclick=async()=>{const url=loginMode?'/api/login':'/api/register';const body={name:$('name').value,email:$('email').value,password:$('password').value};const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return alert(d.error);accountId=d.accountId;name=d.name;localStorage.setItem('bhachuAccount',accountId);localStorage.setItem('bhachuName',name);showApp()};
$('logout').onclick=()=>{localStorage.clear();location.reload()};
async function load(){const a=await (await fetch('/api/account/'+accountId)).json();$('balance').textContent='$'+Number(a.balance).toFixed(2);$('equity').textContent='$'+Number(a.equity).toFixed(2);$('accountId').textContent=a.id;const o=await (await fetch('/api/orders/'+accountId)).json();$('count').textContent=o.filter(x=>x.status==='OPEN').length;$('orders').innerHTML=o.length?o.map(x=>`<div class="order"><span><b>${x.symbol}</b> · <span class="${x.side==='BUY'?'buy':'sell'}">${x.side}</span> · ${x.lots} lots</span><span>${x.status} ${x.status==='OPEN'?`<button onclick="closeOrder('${x.id}')" style="width:auto;padding:6px 9px;margin:0 0 0 8px">Close</button>`:''}</span></div>`).join(''):'<p class="muted">No orders yet.</p>'}
$('order').onclick=async()=>{const body={accountId,symbol:$('symbol').value,side:$('side').value,lots:$('lots').value,price:$('price').value,stopLoss:$('sl').value,takeProfit:$('tp').value};const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return alert(d.error);load()};
window.closeOrder=async id=>{await fetch('/api/orders/'+id+'/close',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({price:$('price').value})});load()};
if(accountId)showApp();
